// Code Generated by Sidekick is for learning and experimentation purposes only.
const express = require('express');
const axios = require('axios');
const LRU = require('lru-cache');
const cors = require('cors');

const app = express();
app.use(cors()); // Allow frontend requests

const cache = new LRU({
  max: 100, // Max cache entries
  ttl: 1000 * 60 * 5 // 5 minutes
});

app.get('/aqi', async (req, res) => {
  const city = req.query.city;
  if (!city) return res.status(400).json({ error: 'City is required' });

  const cacheKey = city.toLowerCase();

  if (cache.has(cacheKey)) {
    return res.json({ source: 'cache', data: cache.get(cacheKey) });
  }

  try {
    // Replace with your real API endpoint and key
    const response = await axios.get(`https://api.example.com/aqi?city=${encodeURIComponent(city)}`);
    const data = response.data;
    cache.set(cacheKey, data);
    res.json({ source: 'api', data });
  } catch (error) {
    res.status(500).json({ error: 'Failed to fetch AQI data' });
  }
});

const PORT = 3000;
app.listen(PORT, () => console.log(`Backend running on port ${PORT}`));
